
- user:
    name: '{{ user }}'
    state: present
  register: user_registered
# tasks file for gvm
- name: Run the equivalent of "apt-get update" as a separate step
  when: ansible_os_family != "Darwin"
  ansible.builtin.apt:
    update_cache: yes

- name: Install pyenv requirements
  when: ansible_os_family != "Darwin"
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - bison
    - build-essential
    - make
    - binutils

- name: Install package mercurial from brew
  become_user: '{{ user }}'
  when: ansible_os_family == "Darwin"
  community.general.homebrew:
    name: mercurial
    state: present

- name: Install gvm
  become_user: '{{ user }}'
  shell: >
    curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
  args:
    creates: "{{ user_registered.home }}/.gvm/bin/gvm"

- name: Install go
  become_user: '{{ user }}'
  when: ansible_os_family != "Darwin"
  shell: source /home/{{ user }}/.gvm/scripts/gvm && gvm install go1.7.1 -B && gvm use go1.7.1 && export GOROOT_BOOTSTRAP=$GOROOT && gvm install go1.19.2 && gvm use go1.19.2 --default
  args:
    executable: /bin/bash
    creates: "{{ user_registered.home }}/.gvm/environments/go1.19.2"

- name: check if lazygit is installed
  become_user: '{{ user }}'
  shell: command -v lazygit
  register: lazygit_exists
  ignore_errors: true

- name: Install lazygit
  when: lazygit_exists is failed
  become_user: '{{ user }}'
  shell: >
    go install github.com/jesseduffield/lazygit@latest
