
# tasks file for gvm
- name: Run the equivalent of "apt-get update" as a separate step
  when: ansible_os_family != "Darwin"
  ansible.builtin.apt:
    update_cache: yes

- name: Install pyenv requirements
  when: ansible_os_family != "Darwin"
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - bison
    - build-essential
    - make
    - binutils
