- hosts: all
  collections:
    - community.general.homebrew
  become: yes
  user: "{{ user }}"
  vars_files:
    - vars/vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
  vars_prompt:
    - name: delete_old_zsh
      prompt: "Do you want to delete zshrc? (yes/no)"
      private: no
  roles:
    - role: basic
    - role: asdf
    - role: neovim
    - name: geerlingguy.docker
      when: ansible_os_family != "Darwin"
