- hosts: all
  collections:
    - community.general.homebrew
  become: yes
  user: "{{ user }}"
  vars_files:
    - vars/vars.yml
  vars:
     ansible_ssh_private_key_file: "{{ private_key }}"
  roles:
    - role: basic
    - role: pyenv
    - role: rust
    - role: node
    - role: tfenv
    - role: golang
    - role: neovim
    - role: docker
