- name: Detects previous installations of asdf
  command: asdf version > /dev/null
  register: asdf_check
  ignore_errors: true
- name: Download and install asdf
  block:
    - name: Clone asdf repository into ~/.asdf
      ansible.builtin.git:
        name: https://github.com/asdf-vm/asdf.git
        dest: '{{ user_registered.home }}/.asdf'
        single_branch: true
    - name: Add plugin asdf
      ansible.builtin.shell: "bash -lc 'source {{ user_registered.home }}/.asdf/asdf.sh && {{ user_registered.home }}/.asdf/bin/asdf plugin add {{ item.name }}  && {{ user_registered.home }}/.asdf/bin/asdf install {{ item.name }} latest' || true"
      with_items: "{{ asdf_plugins }}"
