- name: check if tfenv is installed
  become_user: '{{ user }}'
  shell: command -v tfenv
  register: tfenv_exists
  ignore_errors: true

- name: Install tfenv x86
  become_user: '{{ user }}'
  shell: >
    git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
  args:
    creates: "{{ user_registered.home }}/.tfenv/bin/tfenv"
  when: ansible_os_family != "Darwin" and tfenv_exists is failed

- name: Install tfenv from brew
  become_user: '{{ user }}'
  when: ansible_os_family == "Darwin" and tfenv_exists is failed
  community.general.homebrew:
    name: tfenv
    state: present

- name: check if kubectl is installed
  become_user: '{{ user }}'
  shell: command -v kubectl
  register: kubectl_exists
  ignore_errors: true

- name: Install kubectl
  when: ansible_architecture != "arm64" and ansible_os_family != "Darwin" and kubectl_exists is failed
  become_user: '{{ user }}'
  shell: >
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && mv kubectl ~/.local/bin/kubectl && chmod +x ~/.local/bin/kubectl
  args:
    creates: "{{ user_registered.home }}/.local/bin/kubectl"

- name: Install kubectl arm
  when: ansible_architecture == "arm64" and ansible_os_family != "Darwin" and kubectl_exists is failed
  become_user: '{{ user }}'
  shell: >
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl" && mv kubectl ~/.local/bin/kubectl && chmod +x ~/.local/bin/kubectl
  args:
    creates: "{{ user_registered.home }}/.local/bin/kubectl"

- name: Install kubectl from brew
  become_user: '{{ user }}'
  when: ansible_os_family == "Darwin" and kubectl_exists is failed
  community.general.homebrew:
    name: kubectl
    state: present

- name: check if terraform is installed
  become_user: '{{ user }}'
  shell: terraform -v
  register: terraform_exists
  ignore_errors: true

- name: Install Terraform
  when: terraform_exists is failed and ansible_os_family != "Darwin"
  become_user: '{{ user }}'
  shell: >
    {{ user_registered.home }}/.tfenv/bin/tfenv install latest

- name: Install Terraform macos
  when: terraform_exists is failed and ansible_os_family == "Darwin"
  become_user: '{{ user }}'
  shell: >
    /opt/homebrew/bin/tfenv install latest

- name: Set default Terraform
  when: terraform_exists is failed and ansible_os_family != "Darwin"
  become_user: '{{ user }}'
  shell: >
    {{ user_registered.home }}/.tfenv/bin/tfenv use latest

- name: Set default Terraform macos
  when: terraform_exists is failed and ansible_os_family == "Darwin"
  become_user: '{{ user }}'
  shell: >
    /opt/homebrew/bin/tfenv use latest
