- name: Run the equivalent of "pacman -Sy" as a separate step
  community.general.pacman:
    update_cache: true

- name: Install yay arch
  community.general.pacman:
    state: present
    name:
      - git 
      - base-devel
      - yay
      - openssh
