- name: Install nvm
  become_user: '{{ user }}'
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "/home/{{ user }}/.nvm/nvm.sh"

- name: Install node LTS
  become_user: '{{ user }}'
  shell: "source  ~/.nvm/nvm.sh && nvm install --lts" 
  args:
    executable: /bin/bash
