
- name: Install required system packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_dist }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: add user to docker group
  shell: 'usermod -aG docker {{ user }}'
